# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Editor
email: joo@joostory.net
description: > # this means to ignore newlines until "baseurl:"
  Editor for blog post
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://editor.joostory.net" # the base hostname & protocol for your site
twitter_username: JooStory
github_username:  joostory

# Build settings
markdown: kramdown
